# Site Settings
title:              "Yarpviz"
tagline:            "A graphical tool for profiling and visualizing Yarp network"
description:        "A graphical tool for profiling and visualizing Yarp network"
baseurl:            #"/Lagrange"
url:                #"http://robotology.github.io/yarpviz/"
github:
  url:              #"https://github.com/robotology/yarpviz"
author:
  name:              "Ali Paikan"
  email:             "ali.paikan@iit.it"
#  twitter:           "paululele"
#  instagram:         "paululele"
  github:            "apaikan"
#  facebook:          "Le.Paul.94"
  linkedin:          "apaikan"
navigation:
- title: About
  url: /about
#- title: Writing
#  url: /writing
#- title: Contact
#  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
